export const SET_GROUPS_LIST_I_AM_IN = 'SET_GROUPS_LIST_I_AM_IN';
export const SET_GROUPS_LIST_I_MANAGE = 'SET_GROUPS_LIST_I_MANAGE';
export const SET_GROUPINFO = 'SET_GROUPINFO';
export const SET_GROUP_USER_INFO = 'SET_GROUP_USER_INFO';
